// Design:      chrono
// File:        chrono_tb.v
// Description: Digital chronometer. Test bench.
// Author:      Jorge Juan-Chico <jjchico@gmail.com>
// Date:        14/06/2010 (initial version)

/*
   Lesson 7.3: Digital chronometer.

   This file contains a test bench for the chronometer module in file
   'chrono1.v'. The most difficult aspect to handle in this test bench is
   that we may need many clock cycles to simulate a few seconds of chronometer
   operation. For example, with a system clock of 50MHz, we would need to
   simulate one billion (10^9) clock cycles for a simulated time of only
   2 seconds. Fortunately, the system frequency in our module is a parameter
   so we will instantiate our unit under test using a system frequency of
   only 1000Hz, meaning 1000 clock cycles per simulated second.

   Additionally, in order to apply our input signals at the appropriate time
   easily, we will use profusely the '@' time control operator and the
   'repeat' statement.
*/

`timescale 1 ns / 1 ps

// System frequency in Hz
/* Macro with the system frequency. It will be passed to the 'chrono' module
 * as the parameter of the same name. Using a macro here makes it easy to
 * change its value at will. */
`define SYSFREQ 1000

// Banco de pruebas

module test ();

    reg clk = 0;    // clock
    reg cl = 0;     // clear (active high)
    reg start = 0;  // enable (active high)
    wire [3:0] h0;  // hundredth units
    wire [3:0] h1;  // hundredth tens
    wire [3:0] s0;  // second units
    wire [3:0] s1;  // second tens

    // Circuit under test
    /* Chronometer instantiation with adjusted system clock frequency. */
    chrono1 #(.SYSFREQ(`SYSFREQ)) uut(.clk(clk), .cl(cl), .start(start),
                            .h0(h0), .h1(h1), .s0(s0), .s1(s1));

    // Output generation and simulation control
    initial begin
        // Waveform generation
        /* This test bench can potentially generate a lot of simulation
         * data, so we will use the FST output format instead of the
         * older VCD. FST files are much more compact than VCD (ten times
         * or more) and faster to generate and read by waveform viewers,
         * but not as widespread as the older VCD format. Here we only
         * define the file name. The ability to generate FST format depends
         * on the simulator. Both Icarus Verilog and Gtkwave suports it. */
        $dumpfile("chrono_tb.fst");
        $dumpvars(0, test);

        // Generamos salida en formato texto
        $display("cl start  SS.CC");
        $monitor("%b  %b      %h%h.%h%h",
                   cl, start, s1, s0, h1, h0);
    end

    // Periodic clock signal
    /* We generate a clock signal of 'SYSFREQ' frequency taking into account
     * that the simulators time unit is the nanosecond (due to the use of
     * 'timescale' above) and that 'SYSFREQ' is in Hz. */
    always
        #(1e9 / `SYSFREQ / 2) clk = ~clk;

    // Inputs
    /* Input transitions are synchronized to the clock falling edges. The
     * following sequence makes an initial clear operation, starts the
     * chronometer for a few seconds, stops the chronometer and executes
     * a stop and a clear operation during the counting process. */
    initial begin
        @(negedge clk)
        cl = 1;                 // clear
        @(negedge clk)
        cl = 0;                 // start
        start = 1;
        /* Esperamos 7 segundos */
        repeat(7 * `SYSFREQ) @(negedge clk);
        start = 0;              // stop
        /* Esperamos 2 segundos */
        repeat(2 * `SYSFREQ) @(negedge clk);
        start = 1;              // continue
        repeat(6 * `SYSFREQ) @(negedge clk);
        cl = 1;                 // clear without stopping
        repeat(1 * `SYSFREQ) @(negedge clk);
        cl = 0;
        repeat(3 * `SYSFREQ) @(negedge clk);
        $finish;
    end

endmodule // test

/*
   EXERCISES

   1. Compile and simulate the examples with:

        $ iverilog chrono1.v chrono_tb.v
        $ vvp a.out -fst

      The simulator will generate a 'chrono_tb.fst' file with the waveforms
      generated by the simulation. The fst format (generated with the '-fst'
      option of 'vpp') is more efficient than the traditional 'vcd' format and
      generates much smaller output files.

   2. Check that the results are correct with:

        $ gtkwave chrono_tb.fst

   3. Modify macro SYSFREQ to a higher value (100000 or 1000000) and execute
      the simulation again. Notice the new simulation time and the size of
      the generated file. Visualize the results with 'gtkwave' and compare the
      results using different values of SYSFREQ.

   4. Study the design of module 'chrono2' in file 'chrono2.v'. Use the test
      bench to simulate 'chrono2' and see if the results are different to
      the results of 'chrono1'. What advantages of disadvantages has 'chrono2'
      over 'chrono1'?

   5. Design a 'chrono3' module (in another file) with the same behavior than
      'chrono1' but using an structural design according to the following
      guidelines:

      - The  module 'chrono3' should have exactly the same inputs and outputs
        than 'chrono1' (it can be simulated with the same test bench).

      - The following elements should be described in independent modules:
        frequency divider, hundredth units counter, hundredth tens counter,
        second units counter and second tens counter. Define the inputs and
        outputs of these modules in a convenient way.

      - Build up the 'chrono3' module by interconnecting the above-mentioned
        sub-modules together with additional logic if necessary.

   6. Simulate 'chrono3' with the same test bench used for 'chrono1' and check
      that their operations are identical.
*/
