= verilog-course.v

== In other languages

* https://gitlab.com/jjchico/curso-verilog.v[Español (Spanish)]

== Introduction

Hi!

This is a basic Verilog course completely written in Verilog language. Other
courses include examples but this one is more a collection of examples
containing a course. Every Verilog file (*.v* extension) is a Verilog coding
example together with comments and brief conceptual descriptions.

The course is divided in units and lessons. The overall structure follows a
traditional digital circuits design course. Some basic digital design concepts
are briefly explained, but it is assumed that the student is familiar with basic
digital design concepts or is studying these along this course.

This course focuses on the Verilog language itself and does not go down
to the implementation of the examples. However, all the examples could be
synthesized using any standard Verilog-compatible digital circuits synthesis
tool.

== Tools

To follow this course you will need to compile and simulate the proposed
examples. This course uses http://www.icarus.com/eda/verilog/[Icarus Verilog]
as simulator and http://gtkwave.sourceforge.net/[Gtkwave] as waveform viewer.
All lessons include detailed instructions to simulate the examples and see the
results using these tools. The instruction below describe how to set-up the
necessary tools in a typical configuration, however, any set of tools that
allows editing text files and simulating Verilog code can be used as an
alternative, including FPGA's manufacturers integrated environments.

== Quick start

=== MS-Windows

The recommended way to use this course in MS-Windows is through the Windows
Subsystem Linux (WSL), a Microsoft product that installs a Linux distribution
inside Windows. MS-Windows VSCode can be used as text editor and development
platform through the WSL extension. The configuration steps are these:

1. Install Microsoft's VSCode if not yet installed. Install also the WSL VSCode
   extension from the extensions repository.

2. Install WSL: open a Power Shell terminal and type the following command:

    wsl --install -d ubuntu
+
It will install the Ubuntu Linux distribution.

3. Open an Ubuntu terminal (find it in the application menu). Proceed to Ubuntu Linux install instructions step 2 below.

=== Ubuntu Linux

1. Open a terminal window and install `codium` (Open Source VS Code), `code` (VS
   Code product from Microsoft) or you preferred development text editor:

    $ sudo snap install codium
+
(Use 'code' to install MS VS Code).

2. Install the necessary packages using the command below:

    $ sudo apt install git iverilog gtkwave

3. Clone the course's repository (change to an appropriate folder if you wish):

    $ git clone --depth 1 https://gitlab.com/jjchico/verilog-course.v.git

4. Change to the courses folder and open the text editor:

    $ cd verilog-course.v
    $ codium .
+
(use `code` instead of `codium` if using VS Code).

5. Open a terminal inside Codium/VS Code so you can run the necessary commands:
   Terminal -> New Terminal.

6. To do the course you only need to go into the *verilog* folder. In this
   folder you can find sub-folders with units and lessons sorted numerically.
   Simply open the files in order and follow the instructions in the comments
   that go with the code. The first lesson is at
   _verilog/01_intro/01-1_hello_world/hello.v_.

Enjoy!

== Contents

=== Unit 1. Hardware description languages fundamentals

  * Lesson 1-1. Introduction to hardware description languages
  * Lesson 1-2. Combinational functions description and simulation
  * Lesson 1-3. Types of descriptions in Verilog

=== Unit 2. Test bench

  * Lesson 2-1. Simulation with a test bench
  * Lesson 2-2. Descriptions comparison with the same test bench

=== Unit 3. Combinational examples

  * Lesson 3-1. Simple automobile alarm system
  * Lesson 3-2. Prime number detector
  * Lesson 3-3. Delay and hazards demonstrator

=== Unit 4. Combinational subsystems

  * Lesson 4-1. Combinational subsystems sample descriptions
  * Lesson 4-2. BCD-7 segments code converter (exercise)
  * Lesson 4.3. Parametrized bin/gray converters
  * Lesson 4-4. Subsystems-based circuit analysis (exercise)

=== Unit 5. Arithmetic circuits

  * Lesson 5-1. Adders design
  * Lesson 5-2. Adder/subtractor design
  * Lesson 5-3. Arithmetic-Logic Unit design

=== Unit 6. Sequential circuits

  * Lesson 6-1. Bistable circuits
  * Lesson 6-2. Bistable circuits comparison
  * Lesson 6-3. Blocking and non-blocking assignments
  * Lesson 6-4. Finite-state machines. Sequence detector
  * Lesson 6-5. Arbiter design

=== Unit 7. Counters and registers

  * Lesson 7-1. Universal register
  * Lesson 7-2. Multi-operation counter design
  * Lesson 7-3. Exercise: digital chronometer design
  * Lesson 7-4. De-bouncers and edge detectors

=== Unit 8. Memories

  * Lesson 8-1. ROM-based multiplier design
  * Lesson 8-2. Asynchronous RAM
  * Lesson 8-3. Synchronous RAM

== CONVENTIONS

  * All files use 4-space code indentation. Lines are a maximum of 80
    characters long to make all files easy to read and edit in a 80 columns
    terminal.

  * The code uses two types of comments with different functions. Type `//\...`
    comments are regular brief code comments. Type `/*\...*/` comments contains
    longer explanations of concepts and use of the Verilog language and are
    the core of the course. These long comments can be deleted from the code
    without affecting its clarity so that the code in the examples could be
    used in your own projects. Long comments can be easily removed from a file
    like in the following example:

        $ awk '/\/\*/,/\*\// {next};{print}' alarm.v > clean/alarm.v

  * This course uses the default Verilog standard that Icarus Verilog uses. It
    is Verilog-2005 (IEEE 1634-2005) at the time of writing. Most examples, if
    not all, will work with any simulator supporting the Verilog-2001 standard,
    though. Any modern Verilog toolchain should support this version at least.

  * The code uses ANSI-style constructions throughout the course (similar to
    ANSI-C) introduced by the Verilog-2001 standard.

== Additional examples

You can find additional examples and practical Verilog designs at the author's
project [verilog-examples](https://gitlab.com/jjchico/verilog-examples).

== Contributions

Contributions to this project are welcome in any format: bug reports, comments,
merge requests, etc.

== Author

2009-2026 Jorge Juan-Chico <jjchico@gmail.com>

== License

This file is part of verilog-course.v. verilog-course.v is free software: you
can redistribute it and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
See http://www.gnu.org/licenses/.